data = {
    "Truecaller_data": {
        "status": True,
        "data": 
            [
            {
                "name": "Pallav Vaniya",
                "phones": [
                    {
                        "e164Format": "+919408974741",
                        "numberType": "MOBILE",
                        "nationalFormat": "094089 74741",
                        "dialingCode": 91,
                        "countryCode": "IN",
                        "carrier": "BSNL",
                        "type": "openPhone",
                    }
                ],
                "addresses": [
                    {
                        "address": "IN",
                        "city": "Gujarat",
                        "countryCode": "IN",
                        "timeZone": "+05:30",
                        "type": "address",
                    }
                ],
            },
        ],
    },
    "eyecon_data": {
        "status": True,
        "message": "Success",
        "timestamp": 1719654603126,
        "data": {
            "fullName": "Dhirajlal Vaniya Ten Chemical",
            "otherNames": [
                {"name": "Dhiru Bombay", "type": ""},
                {"name": "Ridhi Shah", "type": ""},
                {"name": "Dhiraj Vania", "type": ""},
            ],
        },
    },
    "whatsapp_data": {
            "status": 200,
            "data": {
                "_id": "6643b2484da487a2398f67f7",
                "number": "918432003083",
                "__v": 0,
                "about": "🙏🏻🚩जय श्रीराम📿🙏🏻🚩",
                "businessProfile": {
                    "id": {
                        "server": "c.us",
                        "user": "918432003083",
                        "_serialized": "918432003083@c.us",
                    },
                    "dataSource": "server",
                    "tag": "1165861054",
                    "description": "Hello Everyone 🙋🏻\u200d♂️,\nMy Name Is Vishnu Nemane, I Am Working In Cyber Security (Ethical Hacking), Digital Forensic Cyber Crime As A Expert 💻,\nI Love In Creating Tech Video Content, Enjoying My Lifestyle, And Make Vlog Every Day.\n\nProfession 💻🕵️ : Ethical Hacker, Digital Forensic Expert, Cyber Crime Investigator, Bug Bounty Hunter, Content Creator …!\n\nYouTube Channel 📸\n“Technical VPN”\n\n📲 @technicalvpn\n\nUse My Business Service And Solved Your Life Problem 💸🙌🏻😃",
                    "categories": [
                        {"id": "1617", "localized_display_name": "Emprendedor(a)"}
                    ],
                    "profileOptions": {
                        "commerceExperience": "catalog",
                        "cartEnabled": True,
                    },
                    "email": "contact.technicalvpn@gmail.com",
                    "website": [
                        "https://www.youtube.com/@technicalvpn",
                        "https://www.youtube.com/@VishnuNemane",
                    ],
                    "latitude": None,
                    "longitude": None,
                    "businessHours": {
                        "config": {
                            "sun": {"mode": "open_24h"},
                            "mon": {"mode": "open_24h"},
                            "tue": {"mode": "open_24h"},
                            "wed": {"mode": "open_24h"},
                            "thu": {"mode": "open_24h"},
                            "fri": {"mode": "open_24h"},
                            "sat": {"mode": "open_24h"},
                        },
                        "timezone": "Asia/Kolkata",
                    },
                    "address": "Mumbai, Maharashtra, India",
                    "fbPage": {},
                    "igProfessional": {},
                    "isProfileLinked": False,
                    "isProfileLocked": True,
                    "coverPhoto": {"id": "261119306959832", "url": {}},
                    "automatedType": "unknown",
                    "welcomeMsgProtocolMode": "none",
                    "prompts": None,
                    "commandsDescription": None,
                    "commands": None,
                },
                "countryCode": "IN",
                "date": "2024-07-27T10:22:23.578Z",
                "id": {
                    "server": "c.us",
                    "user": "918432003083",
                    "_serialized": "918432003083@c.us",
                },
                "isBlocked": False,
                "isBusiness": False,
                "isGroup": False,
                "isMe": False,
                "isMyContact": False,
                "isUser": True,
                "isWAContact": True,
                "labels": [],
                "phone": "+91 84320 03083",
                "profilePic": "https://pps.whatsapp.net/v/t61.24694-24/410129510_892390632504926_7052409955103583905_n.jpg?ccb=11-4&oh=01_Q5AaIKWwSX1FMFVuRhtjh_CyiCPBnf_5zcKoQ69Ti1cPCiMF&oe=66B1E5A8&_nc_sid=e6ed6c&_nc_cat=105",
                "type": "in",
                "isEnterprise": False,
            },
        },
    "social_media_accounts": {
        "success": True,
        "data": {
            "number": 36200130525,
            "valid": True,
            "disposable": False,
            "type": "mobile",
            "country": "HU",
            "carrier": "Yettel Hungary",
            "score": 4,
            "account_details": {
                "facebook": {"registered": False},
                "google": {"registered": False, "account_id": None, "full_name": None},
                "twitter": {"registered": False},
                "instagram": {"registered": False},
                "yahoo": {"registered": None},
                "microsoft": {"registered": False},
                "snapchat": {"registered": False},
                "skype": {
                    "registered": False,
                    "age": None,
                    "city": None,
                    "bio": None,
                    "country": None,
                    "gender": None,
                    "language": None,
                    "name": None,
                    "handle": None,
                    "id": None,
                    "photo": None,
                    "state": None,
                },
                "whatsapp": {
                    "registered": False,
                    "photo": None,
                    "last_seen": None,
                    "about": None,
                    "last_active": None,
                },
                "telegram": {"registered": None, "photo": None, "last_seen": None},
                "viber": {"registered": None, "photo": None, "last_seen": None, "name": None},
                "kakao": {"registered": None},
                "ok": {"registered": False, "age": None},
                "zalo": {"registered": False, "date_of_birth": None, "name": None, "uid": None},
                "line": {"registered": None, "name": None, "photo": None},
                "flipkart": {"registered": True},
                "bukalapak": {"registered": False},
                "jdid": {"registered": None},
                "altbalaji": {"registered": False},
                "shopclues": {"registered": False},
                "snapdeal": {"registered": None},
                "tiki": {"registered": False},
                "vkontakte": {"registered": False},
                "ajio": {"registered": False},
                "makemytrip": {"registered": False},
                "zee5": {"registered": False},
            },
        },
    },
}