data = {
    "Truecaller_data": {
        "status": True,
        "data": 
            [
            {
                "name": "Pallav Vaniya",
                "phones": [
                    {
                        "e164Format": "+919408974741",
                        "numberType": "MOBILE",
                        "nationalFormat": "094089 74741",
                        "dialingCode": 91,
                        "countryCode": "IN",
                        "carrier": "BSNL",
                        "type": "openPhone",
                    }
                ],
                "addresses": [
                    {
                        "address": "IN",
                        "city": "Gujarat",
                        "countryCode": "IN",
                        "timeZone": "+05:30",
                        "type": "address",
                    }
                ],
            },
        ],
    },
    "eyecon_data": {
        "status": True,
        "message": "Success",
        "timestamp": 1719654603126,
        "data": {
            "fullName": "Dhirajlal Vaniya Ten Chemical",
            "otherNames": [
                {"name": "Dhiru Bombay", "type": ""},
                {"name": "Ridhi Shah", "type": ""},
                {"name": "Dhiraj Vania", "type": ""},
            ],
        },
    },
    "whatsapp_data": {
        "id": {
            "server": "c.us",
            "user": "919408974741",
            "_serialized": "919408974741@c.us",
        },
        "number": "919408974741",
        "isBusiness": False,
        "labels": [],
        "type": "in",
        "isMe": False,
        "isUser": True,
        "isGroup": False,
        "isWAContact": True,
        "isMyContact": False,
        "isBlocked": False,
        "profilePic": "https://pps.whatsapp.net/v/t61.24694-24/367555120_210530571776920_4035442803451311132_n.jpg?ccb=11-4&oh=01_Q5AaINyRbt9-vnj489fJLv7gKqZGSAATgWS32B_BZeVC9hik&oe=668CDFE3&_nc_sid=e6ed6c&_nc_cat=106",
        "about": "There is no place like 127.0.0.1",
        "countryCode": "IN",
        "phone": "+91 94089 74741",
    },
    "social_media_accounts": {
        "success": True,
        "data": {
            "number": 36200130525,
            "valid": True,
            "disposable": False,
            "type": "mobile",
            "country": "HU",
            "carrier": "Yettel Hungary",
            "score": 4,
            "account_details": {
                "facebook": {"registered": False},
                "google": {"registered": False, "account_id": None, "full_name": None},
                "twitter": {"registered": False},
                "instagram": {"registered": False},
                "yahoo": {"registered": None},
                "microsoft": {"registered": False},
                "snapchat": {"registered": False},
                "skype": {
                    "registered": False,
                    "age": None,
                    "city": None,
                    "bio": None,
                    "country": None,
                    "gender": None,
                    "language": None,
                    "name": None,
                    "handle": None,
                    "id": None,
                    "photo": None,
                    "state": None,
                },
                "whatsapp": {
                    "registered": False,
                    "photo": None,
                    "last_seen": None,
                    "about": None,
                    "last_active": None,
                },
                "telegram": {"registered": None, "photo": None, "last_seen": None},
                "viber": {"registered": None, "photo": None, "last_seen": None, "name": None},
                "kakao": {"registered": None},
                "ok": {"registered": False, "age": None},
                "zalo": {"registered": False, "date_of_birth": None, "name": None, "uid": None},
                "line": {"registered": None, "name": None, "photo": None},
                "flipkart": {"registered": True},
                "bukalapak": {"registered": False},
                "jdid": {"registered": None},
                "altbalaji": {"registered": False},
                "shopclues": {"registered": False},
                "snapdeal": {"registered": None},
                "tiki": {"registered": False},
                "vkontakte": {"registered": False},
                "ajio": {"registered": False},
                "makemytrip": {"registered": False},
                "zee5": {"registered": False},
            },
        },
    },
}